Class refactor
godiarksel/book-collection pull request #2
Opened 2022-06-02 16:36 UTC by godiarksel

Refactored book collection application to use a Javascript class instead of objects and arrays

2022-06-02 17:05 UTC, youmari requested changes
Hi @godiarksel , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great title and short summary 
✔️ Github flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 17:05 UTC, youmari commented on script.js
> +      // localStorage.clear();
- [ ] please it would be better if you remove the unused commented code in order to keep you file clean and professional

2022-06-02 17:05 UTC, youmari commented on script.js
> +// console.log(oneBook);
- [ ]  please it would be better if you remove the unused commented code in order to keep you file clean and professional

2022-06-02 17:05 UTC, youmari commented on script.js
> +            localStorage.setItem('Book List', JSON.stringify(collection));
- [ ] please make sure when the page is reloaded the books should be stored and retrieved from local storage

2022-06-03 09:08 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @godiarksel and @MicroverseNelson 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 09:25 UTC, merged